# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-05 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import wger.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_mealitem_meal_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='time',
            field=wger.utils.fields.Html5TimeField(blank=True, null=True, verbose_name='Time (approx)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_choice',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Consumed', 'Consumed')], default='Planned', max_length=10),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='meal_choice',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Consumed', 'Consumed')], default='Planned', max_length=10),
        ),
    ]
