# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-13 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_auto_20180305_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='was_planned',
            field=models.BooleanField(default=False),
        ),
    ]
