# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-28 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180222_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_users_via_api',
            field=models.BooleanField(default=False, help_text='Check to enable ability to create users via API', verbose_name='Whether user can create other users via API'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_via_api',
            field=models.BooleanField(default=False, help_text='Check to indicate whether user was created via API', verbose_name='Whether user was created via API'),
        ),
    ]
