# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180228_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_via_api',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.BooleanField(default=False, help_text='Check to indicate whether user was created via API', verbose_name='Whether user was created via API'),
        ),
    ]
