# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180306_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_create_users_via_api',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_use_api_to_create_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_by',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
