# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180306_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='can_use_api_to_create_user',
            new_name='can_add_user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_by',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='added_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
