# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-27 12:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180222_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='use_periodization',
            field=models.BooleanField(default=False, help_text='Divide your annual training plan into specific time blocks. eg(microcycle, mesocycle, macrocycle)'),
        ),
        migrations.AddField(
            model_name='schedulestep',
            name='is_periodized',
            field=models.BooleanField(default=False, help_text='indicates whether the schedule step was created as a cycle in periodization'),
        ),
        migrations.AlterField(
            model_name='schedulestep',
            name='duration',
            field=models.IntegerField(default=4, help_text='The duration in weeks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Duration'),
        ),
    ]
