# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-05 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_workoutsession_workout_log'),
        ('manager', '0009_auto_20180227_1514'),
    ]

    operations = [
    ]
